version: '3.8'

services:
  db:
    image: postgres:17
    container_name: teledoc-db
    environment:
      POSTGRES_PASSWORD: teledoc
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: TeleDoc.API/Dockerfile
    container_name: teledoc-api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=teledoc
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./TeleDoc.API/appsettings.json:/app/appsettings.json

volumes:
  pgdata: